# Generated by Django 5.2.6 on 2025-09-30 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_schoolclass_to_grade_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='grade',
            field=models.PositiveSmallIntegerField(help_text='Class/Grade number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(help_text='Section letter, e.g., A, B, C', max_length=2),
        ),
    ]
