# Generated by Django 5.2.6 on 2025-10-08 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schoolclass_grade_alter_schoolclass_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualExcuseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_excuse_logs', to='core.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_excuse_logs', to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_excuse_logs', to='core.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'date'], name='core_manual_teacher_10dfb9_idx')],
            },
        ),
    ]
